global using System.Text;
global using eSystem.Core.Common.Results;
global using eSystem.Core.Security.Authentication.Constants;
global using eSystem.ServiceDefaults;
global using FluentValidation;
global using MediatR;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Options;
global using Microsoft.IdentityModel.Tokens;
global using Scalar.AspNetCore;
global using Results = eSystem.Core.Common.Results.Results;
global using TokenOptions = eSecurity.Server.Security.Cryptography.Tokens.TokenOptions;