global using eShop.Application.Extensions;
global using eShop.Application.Utilities;
global using eShop.Domain.Abstraction.Data;
global using eShop.Domain.Common.API;
global using eShop.Domain.Enums;
global using eShop.Product.Api.Behaviours;
global using eShop.Product.Api.Data;
global using eShop.Product.Api.Entities;
global using eShop.Product.Api.Extensions;
global using eShop.Product.Api.Features.Product;
global using eShop.Product.Api.Interfaces;
global using eShop.ServiceDefaults;
global using FluentValidation;
global using MassTransit;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using Newtonsoft.Json;
global using Response = eShop.Domain.Common.API.Response;
global using Results = eShop.Domain.Common.API.Results;