global using System.Text;
global using eSystem.ServiceDefaults;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Options;
global using Microsoft.IdentityModel.Tokens;
global using Scalar.AspNetCore;
global using OAuthFlow = eSecurity.Core.Security.Authorization.OAuth.OAuthFlow;
global using Results = eSystem.Core.Http.Results.Results;
global using SessionOptions = eSecurity.Server.Security.Authentication.OpenIdConnect.Session.SessionOptions;