global using System.Text;
global using eSystem.ServiceDefaults;
global using MediatR;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Options;
global using Microsoft.IdentityModel.Tokens;
global using Scalar.AspNetCore;
global using Results = eSystem.Core.Http.Results.Results;
global using TokenOptions = eSecurity.Server.Security.Cryptography.Tokens.TokenOptions;