export interface UserInfo {
  sub: string,
  name?: string,
  given_name?: string,
  family_name?: string,
  middle_name?: string,
  nickname?: string,
  profile?: string,
  gender?: string,
  birthdate?: string,
  updated_at?: number,
  zoneinfo?: string,
  locale?: string,
  preferred_username?: string,
  email?: string,
  email_verified?: boolean,
  phone?: string,
  phone_verified?: boolean,
  address?: {
    street_address: string,
    locality: string,
    region: string,
    postal_code: string,
    country_code: string,
  }
}
