global using System.Text;
global using eSecurity.Common.Mapping;
global using eSecurity.Data;
global using eSecurity.Features.Security.Commands;
global using eSystem.Core.Common.Results;
global using eSystem.Core.Enums;
global using eSystem.ServiceDefaults;
global using FluentValidation;
global using MediatR;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Options;
global using Microsoft.IdentityModel.Tokens;
global using Scalar.AspNetCore;
global using HttpOptions = eSystem.Core.Common.Http.HttpOptions;
global using HttpRequest = eSystem.Core.Common.Http.HttpRequest;
global using HttpResponse = eSystem.Core.Common.Http.HttpResponse;
global using Results = eSystem.Core.Common.Results.Results;